name: Update Last Spotify Song

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      - name: Set up Spotify credentials
        run: |
          echo "SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}" >> .env
          echo "SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}" >> .env
          echo "SPOTIPY_REDIRECT_URI=${{ secrets.SPOTIPY_REDIRECT_URI }}" >> .env
          echo "${{ secrets.SPOTIFY_CACHE }}" > .spotify_cache
      - name: Export last played song
        run: python export_last_song_github_pages.py
        continue-on-error: true
      - name: Check if export succeeded
        run: |
          if [ ! -f docs/last_song.json ]; then
            echo "❌ Export failed - no JSON file created"
            echo "This might happen if the refresh token expired (after ~6 months)"
            echo "Please re-authenticate and update the SPOTIFY_CACHE secret"
            exit 1
          else
            echo "✅ Export successful"
          fi
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/last_song.json
          git commit -m "Update last played song [skip ci]" || echo "No changes to commit"
          git push
